# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: "maven"
    # Look for `requirements.*` files in the `root` directory
    directory: "/"
    # Check the registry for updates every week
    schedule:
      interval: "weekly"
    # Add labels to generated PRs
    labels:
      - "dependencies"
    # Spring-boot updates are always considered separately, regardless of semver level,because of the many transitive dependencies.
    # Other *major* updates are also considered separately because they often require closer scrutiny.
    # Non-major updates are grouped to reduce the number of PRs.
    # Note that group rules are applied in order, so the first match wins.
    groups:
      spring-boot:
        applies-to: version-updates
        patterns:
          - "*spring-boot-starter-parent*"
      major:
        applies-to: version-updates
        update-types:
          - "major"
        patterns:
          - "*"
      non-major:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
