# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: "maven"
    # Where to look for the pom.xml
    directory: "/"
    # How often to check the registry for updates
    schedule:
      interval: "daily"
    # Which labels to add to generated PRs
    labels:
      - "dependencies"
    # Group minor updates and patch updates, except for spring-boot-starter-parent updates,
    # and create separate PRs for updates that do not match any grouping rule.
    groups:
      minor-or-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "*spring-boot-starter-parent*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    allow:
      # don't do major upgrades
      - dependency-name: "*eclipse-temurin*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
