services:
    mongo:
        ports:
            - '27017:27017'
        container_name: fdp-mongo
        restart: always
        logging:
            options:
                max-size: 1g
        image: mongo
