/**
 * The MIT License
 * Copyright © 2017 FAIR Data Team
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.fairdatateam.fairdatapoint.service.search;

import org.fairdatateam.fairdatapoint.BaseIntegrationTest;
import org.fairdatateam.fairdatapoint.entity.search.SearchSavedQuery;
import org.fairdatateam.fairdatapoint.service.search.query.SearchSavedQueryService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;

import static org.junit.jupiter.api.Assertions.assertNotNull;

public class SearchSavedQueryServiceTests extends BaseIntegrationTest {

    private final SearchSavedQueryService savedQueryService;

    /**
     * Constructor
     */
    // constructor injection in junit tests requires explicit @Autowired annotation
    @Autowired
    public SearchSavedQueryServiceTests(SearchSavedQueryService savedQueryService) {
        this.savedQueryService = savedQueryService;
    }

    @Test
    public void testCreateAutogeneratedValues() {
        final SearchSavedQuery savedQuery = new SearchSavedQuery();
        SearchSavedQuery newSavedQuery = savedQueryService.create(savedQuery);
        assertNotNull(newSavedQuery.getUuid());
        assertNotNull(newSavedQuery.getUserUuid());
        assertNotNull(newSavedQuery.getCreatedAt());
        assertNotNull(newSavedQuery.getUpdatedAt());
    }
}
