ping:
  enabled: false

security:
  jwt:
    token:
      expiration: 999

spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/fdp
    username: fdp
    password: fdp
  flyway:
    locations: classpath:dev/db/migration,classpath:db/migration
    fail-on-missing-locations: true
    clean-disabled: false
