instance:
  index: false
  clientUrl: http://localhost:8080
  behindProxy: true

spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/fdp
    web:
      pageable:
        default-page-size: 50
        qualifier-delimiter: _
  task:
    execution:
      pool:
        core-size: 2
        max-size: 5
        queue-capacity: 5000
      thread-name-prefix: fdp-task-

management:
  health:
    solr:
      enabled:  false
  info:
    defaults:
      enabled: false

security:
  jwt:
    token:
      secret-key: IBQADE2IGQAWYWPUR2RTLCE2GSUST8MNLYM6XJJ0442SO8LBQ0Y5NSSZPDMEEJ9DH5EXL02AZCZWGOWH5RY23BDT7WBBMVC607DTANIJ3VH8KD6JDOLW03G68Q5Z2Y430QV76RBCIM3TIFGP32Y33QR3LFXEGGII2UQOZFQFOZ2NZ9KLDHJLAAOU2PH82PVH7DTBNLTQD30HQG6OI09O9LT9BDKIYYB10TO2MDDS1MZ0C77O8OQDDLAXDK8LFWGMZSK4MAUJNLPTMVGX5CSVXAGNDBFNSZNGA37XSCP7JAYR8AQQDEHM5GOB3AIBOKDQ3BJ3GORFAZOHU3EJU2JBFY5JH8BM8QEUCQ6XZEE6SWO28HSNWVHV8UB3Z0M46BX7K0UM9HJJQ3I3R1KGTSRTR3U4XTTDHPKRBNGZ8HM4ZTJOOF26KFE21Q9C2LQD6OZRZ5REOYKGN2V47OLYPO2QB6982TPEE8HVBOJ7I9GE4MHG0BFMO9UKSZA5P17KR4TLBKXG51AB4DWQPK445FX7ZLBV6KSUUNDSCQI7PVI31MMET8168WGEN25WWUHSEB5KVLQH53BVJ0P7B0NHJOY31DH5F2ZUIAVFFE6MRPZAUHYRY5LQLFUFB1MF0MX6J61WEPC5MBLCD1JN9UP35HSHR8Z3YHTBP388DSGPX74C88S4A3BTK8PIIQ3TQKL819VL7LOHXJL1FODC1TGW0KGBV8XRPPV5K75KG5MJM7E3WMXDEY5G4PJYNLT5G67257X1RONPG518N76CBXUQBTYTBYH81PBHD0O09PY3R5X9IDDI4FBIAX4WANZSRLUQNJT4EI7W8AYHZ16P2O769O4GS2ECL3IDUPVYCFINAC2E1Q80P1PVZNLDFF9440E0Q27375NK5NLZQQCJXBB8J4QPFI78TW2MH9O5OVQ04506FWBUCLK3O6Q3XCXKBJRPLZBB6SVKXCOYELQQA0U5QBW4VNYNHY4TFZ8RDSNVULB5GV35432IAFKAQBL1KVA7LJBMAN06EFXW303MYYGKEH2URL02RHRDHROQHAH4TY76F1R9RKPVF620MYMBNF9LNC96U7PX2E5WCO7B778ZYT6RZKMPHP5FRG3LT0HSY540ZN91B1ACZAID1JTJKWOIGQSKPQEO3ORDNI2WQMPNTI7KJL6CP53VXFVM0M54F1IVK0V1M7QIUXVJ3VC6XNFDMV77I8DOL926SNS5Z952LGQFVPSS60X7MMPJ8PNNT0BX4B14CYT5E3832H8YOATAHD9PFD30ELYJV4S6RDZ0D6CJWM5KQGBCXHXAB98Z4DYWGAC5T7K5N17SWAT86VU3VNP8AJP2AGZVFBBEI3MCP7RW7Z1DR85YI6CMW7M8MUAWB66LWU6NAZ4PW4FSD443KX15FYYRZDPDNGKLVZY5680G0TCW76N40D1JU4GBLCWASIHEU110XZZ0OLYLHCJCQGELT7Y5B10VBRVWW48Q6AGJ0T85Y73RCCPBJSU73UAN51R0E65RF6OQGNOY6RDHCI06S8EO6AMZMK503M0ORDFSH8BE6NE9J2022ZSFEO0FM513SLKUSYPK4NG0FJIBCR3T0Y7CIOF6WDA5AA9JY615PQPRD38E0GDFM2A1XIU9Y5LR71F69VZPC5CXJZOXVB2T6WQNJDEN8KBGK1R55IOLBK6LYPVB1SOWM26K46OM39ZZX5H8D4OMAX9B6MHKQD0D4V8VNTQO5P0MRE39YUC231T87HCJDILC8IBS6LB2PC7F8C5TYLZ2Q8RKC015I4JX3SAOFZIPGGD0Q5HQYH1PVYIVU43QNK2N5O13NPMF6NT6BHK4GXR52IZLYWD9KR0UAZJ1YCL7COD2VF4AI1SMP0PZPODVQVGX7BFEVRBS9XKI1TAWLEGRSYD5XBLWH91YPFIUDVCOJT4RQJOHV9QRM32BJYMBTTJYN42NFKF6SRXWHXIKMMDEHXCUECAJW70A6UM0QEIC988M03FJ5RY34VUPQ30NV23QJVCZ1PR81N8BT2VNCDOONYSS33YKW0QBUGJ2HX7UAP1TQN49GEC6GUP0I434S6DQZEEY06MRF0QLIU79F2HWN2XG5Q9X6VXRTEA7PT3X78CY5YM3N2LX81Y10NQC5U1NZYZQD2NV347MTSFO8MECHODX6OX3LCKIQELAOMQ7DVD6I1MJUWG5DI8TC1OL4JMGJOCY7J4GAOY5SXNBLF39REZQYP7IW5G8943QQD6FICJWBSHO8Y7Z745UXJIWZ4WPB3TB4355UP4O0EU6WFSMPUNJK8GN8FJHCQTOKTCNZA6L77JMNUMIP70QM525H815U7YH3JPXJ4NDH1YAVKR9OYRKDKN64843DGKW7HDN1KOGG2I41G8K2AKRWTFR69HC3WHZEX0MQ7YNQF5RVIDFH503388FLJVM778DTR23754Y62EAX9OBY10YDWHRHRQQDR5NQX9A07T9ZLZ9AI59WFEUM2GQAH1ZA9ELZB3OW7LB961300QVUOYAJWWMMRFOFGX6QYTB4IBM3PACQCJSFTK4K3YRUS5R

# valid repository type options {1 = inMemoryStore, 2 = NativeStore, 3 = AllegroGraph, 4 = graphDB, 5 = blazegraph}
repository:
  type: 1
  native:
    dir: /tmp/fdp-store/
  agraph:
    url: http://localhost:10035/repositories/fdp
    username: user
    password: password
  graphDb:
    url: http://localhost:7200
    repository: test
  blazegraph:
    url: http://localhost:8888/blazegraph
    repository:

metadataProperties:
  language: http://id.loc.gov/vocabulary/iso639-1/en
  license: http://rdflicense.appspot.com/rdflicense/cc-by-nc-nd3.0
  accessRightsDescription: This resource has no access restriction

openapi:
  title: FAIR Data Point API
  version: 1.11.0
  description: "The reference implementation of the metadata registration service: A service implementing the API specification. It contains an authentication system to allow maintainers to define and update metadata. Read-only access to the data is public."
  contact:
    name: Luiz Bonino
    email: luiz.bonino@go-fair.org
    url: https://github.com/FAIRDataTeam/FAIRDataPoint

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    operationsSorter: alpha

server:
  forward-headers-strategy: framework
