name: Feature Request
description: Propose a new feature that would improve FDP
title: "New feature"
labels: ["Feature Request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please check [previous questions](https://github.com/FAIRDataTeam/FAIRDataPoint/issues?q=is%3Aissue+label%3AFeature%20Request+) first if you cannot already find an answer there.
  - type: textarea
    id: question
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: What solution you'd like?
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: What alternatives have you considered?
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: question
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
