services:
     fdp:
         image: fairdata/fairdatapoint:1.16
         volumes:
             - ./application.yml:/fdp/application.yml:ro
             - ./rdf/data:/fdp/fdp-store

     fdp-client:
         image: fairdata/fairdatapoint-client:1.16
         ports:
             - 80:80
         environment:
             - FDP_HOST=fdp
         volumes:
            # Mount new logo file to assets in the container
            - type: bind
              source: ./eh-next_logo.png
              target: /usr/share/nginx/html/assets/my-logo.png, readonly

            # Mount _variables.scss so that styles are regenerated
            - type: bind
              source: ./_variables.scss
              target: /src/scss/custom/_variables.scss, readonly

     mongo:
         image: mongo:4.2.24
         volumes:
             - ./mongo/data:/data/db
