PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT ?entity ?rdfType ?title ?description ?relationPredicate ?relationObject WHERE {
    ?entity ?relationPredicate ?relationObject .
    ?entity rdf:type ?rdfType .
    ?entity dct:title ?title .

    OPTIONAL { ?entity dct:description ?description }
    FILTER isLiteral(?relationObject)
    FILTER CONTAINS(LCASE(str(?relationObject)), LCASE(str(?query)))
}
