name: Publish to Docker Hub

on:
  pull_request:
  release:
    types: [created]

jobs:
  # todo: enable test when test duration has been minimized
  # test:
  #   uses: FAIRDataTeam/github-workflows/.github/workflows/maven-verify.yml@v2
  publish:
    # needs: test
    # todo: use version instead of branch (after release of github-workflows v2)
    uses: FAIRDataTeam/github-workflows/.github/workflows/docker-publish.yml@main
    secrets: inherit
    with:
      push: ${{ github.event_name == 'release' && github.event.action == 'created' }}
