name: Publish to Docker Hub

on:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    uses: FAIRDataTeam/github-workflows/.github/workflows/maven-verify.yml@v2
    with:
      # todo: enable tests when test duration has been minimized
      mvn-options: "-DskipTests"
  publish:
    needs: build
    uses: FAIRDataTeam/github-workflows/.github/workflows/docker-publish.yml@v2
    secrets: inherit
    with:
      file: './Dockerfile.build'
      push: ${{ github.event_name == 'release' && github.event.action == 'created' }}
