# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-java-with-maven

name: Maven CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    strategy:
      matrix:
        runner:
          - ubuntu-24.04
          - windows-2022
          - macos-14
        java-version:
          - 21
    # todo: specify version instead of temporary branch
    uses: FAIRDataTeam/github-workflows/.github/workflows/maven-verify.yml@issue5-inputs
    with:
      runner: ${{ matrix.runner }}
      java-version: ${{ matrix.java-version }}
